# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(815, 536)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 294, 421))
        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 60, 20, 281))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.groupBox)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(20, 50, 261, 20))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 270, 91, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 150, 71, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 190, 71, 16))
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(20, 330, 261, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, 30, 55, 16))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 230, 61, 16))
        self.pollo_pro_spinBox = QSpinBox(self.groupBox)
        self.pollo_pro_spinBox.setObjectName(u"pollo_pro_spinBox")
        self.pollo_pro_spinBox.setGeometry(QRect(120, 70, 51, 22))
        self.pollo_pro_spinBox.setMinimum(0)
        self.pollo_pro_spinBox.setMaximum(500)
        self.line_3 = QFrame(self.groupBox)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(270, 60, 20, 281))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 310, 91, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 110, 55, 16))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 30, 71, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(120, 30, 71, 16))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 70, 41, 16))
        self.taco_pro_spinBox = QSpinBox(self.groupBox)
        self.taco_pro_spinBox.setObjectName(u"taco_pro_spinBox")
        self.taco_pro_spinBox.setGeometry(QRect(120, 110, 51, 22))
        self.taco_pro_spinBox.setMinimum(0)
        self.taco_pro_spinBox.setMaximum(500)
        self.pescuezo_pro_spinBox = QSpinBox(self.groupBox)
        self.pescuezo_pro_spinBox.setObjectName(u"pescuezo_pro_spinBox")
        self.pescuezo_pro_spinBox.setGeometry(QRect(120, 150, 51, 22))
        self.pescuezo_pro_spinBox.setMinimum(0)
        self.pescuezo_pro_spinBox.setMaximum(500)
        self.papa_pro_spinBox = QSpinBox(self.groupBox)
        self.papa_pro_spinBox.setObjectName(u"papa_pro_spinBox")
        self.papa_pro_spinBox.setGeometry(QRect(120, 190, 51, 22))
        self.papa_pro_spinBox.setMinimum(0)
        self.papa_pro_spinBox.setMaximum(500)
        self.mole_pro_spinBox = QSpinBox(self.groupBox)
        self.mole_pro_spinBox.setObjectName(u"mole_pro_spinBox")
        self.mole_pro_spinBox.setGeometry(QRect(120, 230, 51, 22))
        self.mole_pro_spinBox.setMinimum(0)
        self.mole_pro_spinBox.setMaximum(500)
        self.ensalada_pro_spinBox = QSpinBox(self.groupBox)
        self.ensalada_pro_spinBox.setObjectName(u"ensalada_pro_spinBox")
        self.ensalada_pro_spinBox.setGeometry(QRect(120, 270, 51, 22))
        self.ensalada_pro_spinBox.setMinimum(0)
        self.ensalada_pro_spinBox.setMaximum(500)
        self.chamorro_pro_spinBox = QSpinBox(self.groupBox)
        self.chamorro_pro_spinBox.setObjectName(u"chamorro_pro_spinBox")
        self.chamorro_pro_spinBox.setGeometry(QRect(120, 310, 51, 22))
        self.chamorro_pro_spinBox.setMinimum(0)
        self.chamorro_pro_spinBox.setMaximum(500)
        self.pollo_sob_spinBox = QSpinBox(self.groupBox)
        self.pollo_sob_spinBox.setObjectName(u"pollo_sob_spinBox")
        self.pollo_sob_spinBox.setGeometry(QRect(220, 70, 51, 22))
        self.pollo_sob_spinBox.setMinimum(0)
        self.pollo_sob_spinBox.setMaximum(500)
        self.taco_sob_spinBox = QSpinBox(self.groupBox)
        self.taco_sob_spinBox.setObjectName(u"taco_sob_spinBox")
        self.taco_sob_spinBox.setGeometry(QRect(220, 110, 51, 22))
        self.taco_sob_spinBox.setMinimum(0)
        self.taco_sob_spinBox.setMaximum(500)
        self.pescuezo_sob_spinBox = QSpinBox(self.groupBox)
        self.pescuezo_sob_spinBox.setObjectName(u"pescuezo_sob_spinBox")
        self.pescuezo_sob_spinBox.setGeometry(QRect(220, 150, 51, 22))
        self.pescuezo_sob_spinBox.setMinimum(0)
        self.pescuezo_sob_spinBox.setMaximum(500)
        self.papa_sob_spinBox = QSpinBox(self.groupBox)
        self.papa_sob_spinBox.setObjectName(u"papa_sob_spinBox")
        self.papa_sob_spinBox.setGeometry(QRect(220, 190, 51, 22))
        self.papa_sob_spinBox.setMinimum(0)
        self.papa_sob_spinBox.setMaximum(500)
        self.mole_sob_spinBox = QSpinBox(self.groupBox)
        self.mole_sob_spinBox.setObjectName(u"mole_sob_spinBox")
        self.mole_sob_spinBox.setGeometry(QRect(220, 230, 51, 22))
        self.mole_sob_spinBox.setMinimum(0)
        self.mole_sob_spinBox.setMaximum(500)
        self.ensalada_sob_spinBox = QSpinBox(self.groupBox)
        self.ensalada_sob_spinBox.setObjectName(u"ensalada_sob_spinBox")
        self.ensalada_sob_spinBox.setGeometry(QRect(220, 270, 51, 22))
        self.ensalada_sob_spinBox.setMinimum(0)
        self.ensalada_sob_spinBox.setMaximum(500)
        self.chamorro_sob_spinBox = QSpinBox(self.groupBox)
        self.chamorro_sob_spinBox.setObjectName(u"chamorro_sob_spinBox")
        self.chamorro_sob_spinBox.setGeometry(QRect(220, 310, 51, 22))
        self.chamorro_sob_spinBox.setMinimum(0)
        self.chamorro_sob_spinBox.setMaximum(500)
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 350, 41, 16))
        self.agregar_fecha_checkBox = QCheckBox(self.groupBox)
        self.agregar_fecha_checkBox.setObjectName(u"agregar_fecha_checkBox")
        self.agregar_fecha_checkBox.setGeometry(QRect(20, 350, 21, 21))
        self.agregar_dateEdit = QDateEdit(self.groupBox)
        self.agregar_dateEdit.setObjectName(u"agregar_dateEdit")
        self.agregar_dateEdit.setGeometry(QRect(120, 350, 110, 22))
        self.agregar_dateEdit.setMaximumDateTime(QDateTime(QDate(2050, 12, 31), QTime(23, 59, 59)))
        self.agregar_dateEdit.setMinimumDateTime(QDateTime(QDate(1992, 1, 1), QTime(0, 0, 0)))
        self.agregar_dateEdit.setMinimumDate(QDate(1992, 1, 1))
        self.agregar_dateEdit.setDate(QDate(2021, 1, 1))
        self.agregar_registro_pushButton = QPushButton(self.groupBox)
        self.agregar_registro_pushButton.setObjectName(u"agregar_registro_pushButton")
        self.agregar_registro_pushButton.setGeometry(QRect(10, 380, 271, 28))
        self.agregar_tableWidget = QTableWidget(self.tab)
        self.agregar_tableWidget.setObjectName(u"agregar_tableWidget")
        self.agregar_tableWidget.setGeometry(QRect(310, 20, 471, 361))
        self.agregar_plainTextEdit = QPlainTextEdit(self.tab)
        self.agregar_plainTextEdit.setObjectName(u"agregar_plainTextEdit")
        self.agregar_plainTextEdit.setGeometry(QRect(610, 400, 171, 31))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(570, 410, 41, 16))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.buscar_dateEdit = QDateEdit(self.tab_2)
        self.buscar_dateEdit.setObjectName(u"buscar_dateEdit")
        self.buscar_dateEdit.setGeometry(QRect(10, 400, 110, 31))
        self.buscar_tableWidget = QTableWidget(self.tab_2)
        self.buscar_tableWidget.setObjectName(u"buscar_tableWidget")
        self.buscar_tableWidget.setGeometry(QRect(10, 20, 761, 341))
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 380, 55, 16))
        self.buscar_pushButton = QPushButton(self.tab_2)
        self.buscar_pushButton.setObjectName(u"buscar_pushButton")
        self.buscar_pushButton.setGeometry(QRect(140, 400, 131, 31))
        self.eliminar_pushButton = QPushButton(self.tab_2)
        self.eliminar_pushButton.setObjectName(u"eliminar_pushButton")
        self.eliminar_pushButton.setGeometry(QRect(290, 400, 131, 31))
        self.label_17 = QLabel(self.tab_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(560, 410, 41, 16))
        self.buscar_plainTextEdit = QPlainTextEdit(self.tab_2)
        self.buscar_plainTextEdit.setObjectName(u"buscar_plainTextEdit")
        self.buscar_plainTextEdit.setGeometry(QRect(600, 400, 171, 31))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_2 = QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 20, 211, 411))
        self.line_5 = QFrame(self.groupBox_2)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 60, 20, 301))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(self.groupBox_2)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(20, 50, 181, 20))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 280, 91, 16))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(30, 160, 71, 16))
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(30, 200, 71, 16))
        self.line_7 = QFrame(self.groupBox_2)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(20, 350, 181, 20))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_18 = QLabel(self.groupBox_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 240, 61, 16))
        self.line_8 = QFrame(self.groupBox_2)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(190, 60, 20, 301))
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_19 = QLabel(self.groupBox_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 320, 91, 16))
        self.label_20 = QLabel(self.groupBox_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(30, 120, 55, 16))
        self.label_21 = QLabel(self.groupBox_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(30, 30, 71, 16))
        self.label_22 = QLabel(self.groupBox_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(120, 30, 71, 16))
        self.label_23 = QLabel(self.groupBox_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 80, 41, 16))
        self.cambiar_precio_pushButton = QPushButton(self.groupBox_2)
        self.cambiar_precio_pushButton.setObjectName(u"cambiar_precio_pushButton")
        self.cambiar_precio_pushButton.setGeometry(QRect(20, 370, 181, 28))
        self.pollo_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.pollo_precio_doubleSpinBox.setObjectName(u"pollo_precio_doubleSpinBox")
        self.pollo_precio_doubleSpinBox.setGeometry(QRect(120, 80, 62, 22))
        self.pollo_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.taco_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.taco_precio_doubleSpinBox.setObjectName(u"taco_precio_doubleSpinBox")
        self.taco_precio_doubleSpinBox.setGeometry(QRect(120, 120, 62, 22))
        self.taco_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.pescuezo_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.pescuezo_precio_doubleSpinBox.setObjectName(u"pescuezo_precio_doubleSpinBox")
        self.pescuezo_precio_doubleSpinBox.setGeometry(QRect(120, 160, 62, 22))
        self.pescuezo_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.papa_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.papa_precio_doubleSpinBox.setObjectName(u"papa_precio_doubleSpinBox")
        self.papa_precio_doubleSpinBox.setGeometry(QRect(120, 200, 62, 22))
        self.papa_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.mole_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.mole_precio_doubleSpinBox.setObjectName(u"mole_precio_doubleSpinBox")
        self.mole_precio_doubleSpinBox.setGeometry(QRect(120, 240, 62, 22))
        self.mole_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.ensalada_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.ensalada_precio_doubleSpinBox.setObjectName(u"ensalada_precio_doubleSpinBox")
        self.ensalada_precio_doubleSpinBox.setGeometry(QRect(120, 280, 62, 22))
        self.ensalada_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.chamorro_precio_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.chamorro_precio_doubleSpinBox.setObjectName(u"chamorro_precio_doubleSpinBox")
        self.chamorro_precio_doubleSpinBox.setGeometry(QRect(120, 320, 62, 22))
        self.chamorro_precio_doubleSpinBox.setMaximum(300.000000000000000)
        self.cambiar_precio_tableWidget = QTableWidget(self.tab_3)
        self.cambiar_precio_tableWidget.setObjectName(u"cambiar_precio_tableWidget")
        self.cambiar_precio_tableWidget.setGeometry(QRect(240, 30, 531, 351))
        self.mostrar_precio_pushButton = QPushButton(self.tab_3)
        self.mostrar_precio_pushButton.setObjectName(u"mostrar_precio_pushButton")
        self.mostrar_precio_pushButton.setGeometry(QRect(240, 390, 181, 28))
        self.tabWidget.addTab(self.tab_3, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 815, 26))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Ord. Ensalada", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Pescuezos", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Ord. Papas", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Sobrante", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Ord. Mole", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Chamorros", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Tacos", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Producto", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Producido", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Pollos", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Fecha", None))
        self.agregar_fecha_checkBox.setText("")
        self.agregar_registro_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar Registro", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Agregar", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Fecha:", None))
        self.buscar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Buscar", None))
        self.eliminar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Eliminar", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Total:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Buscar y eliminar", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Cambiar precio", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Ord. Ensalada", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Pescuezos", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Ord. Papas", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Ord. Mole", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Chamorros", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Tacos", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Producto", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Precio", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Pollos", None))
        self.cambiar_precio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Cambiar Precio", None))
        self.mostrar_precio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar precios", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Cambiar precio", None))
    # retranslateUi

